### ISSUE TITLE
Routing error in Redmine trunk@8761

### ISSUE THREAD

**Issue by jwalkerbg** [cforce/projects_tree_view#2] opened 2012-02-04 07:07 UTC
here is the log:

=== START LOG ===
Processing ProjectsController#index (for 192.168.2.100 at 2012-02-04 09:04:50) [GET]
  Parameters: {"action"=>"index", "controller"=>"projects"}
Rendering template within layouts/base
Rendering projects/index

ActionView::TemplateError (No route matches {:action=>"index", :controller=>"time_entries"}) on line #11 of vendor/plugi
ns/projects_tree_view/app/views/projects/index.rhtml:
8:       <%= link_to(l(:label_project_new), {:controller => 'projects', :action => 'new'}, :class => 'icon icon-add') +
' |' if User.current.admin? %>
9:     <% end %>
10:     <%= link_to(l(:label_issue_view_all), { :controller => 'issues' }) + ' |' if User.current.allowed_to?(:view_issu
es, nil, :global => true) %>
11:     <%= link_to(l(:label_overall_spent_time), { :controller => 'time_entries' }) + ' |' if User.current.allowed_to?(
:view_time_entries, nil, :global => true) %>
12:     <%= link_to l(:label_overall_activity), { :controller => 'activities', :action => 'index' }%>
13: </div>
14:

```
vendor/plugins/projects_tree_view/app/views/projects/index.rhtml:11:in `_run_rhtml_vendor47plugins47projects_tree_vi
```

ew47app47views47projects47index46rhtml'
    d:/Ruby187/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
    d:/Ruby187/lib/ruby/1.8/webrick/httpserver.rb:65:in`run'
    d:/Ruby187/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
    d:/Ruby187/lib/ruby/1.8/webrick/server.rb:162:in`start'
    d:/Ruby187/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
    d:/Ruby187/lib/ruby/1.8/webrick/server.rb:95:in`start'
    d:/Ruby187/lib/ruby/1.8/webrick/server.rb:92:in `each'
    d:/Ruby187/lib/ruby/1.8/webrick/server.rb:92:in`start'
    d:/Ruby187/lib/ruby/1.8/webrick/server.rb:23:in `start'
    d:/Ruby187/lib/ruby/1.8/webrick/server.rb:82:in`start'

Rendering D:/biz/apps/redmine_trunk/public/500.html (500 Internal Server Error)
=== END LOG ===

**Comment by cforce** [comment] 2012-02-05 12:33
dupe of #1

**Closed as completed by cforce** 2012-02-05 12:33 UTC
